name: Check disabled tests
run-name: Checking for closed issues referenced in source at ${{ github.ref }} 🚀
on: 
    issues:
      types:
        - closed 
jobs:
 CheckDisabledTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grep for the issue 
        run : grep -rHn "#${{ github.event.issue.number }}" --include="*.cs" . > sources-referencing-closed-issues.txt || true
      - name: Checking grep resuls
        uses : actions/github-script@v6
        with: 
          script: |
            const fs = require('fs');
              
            // Read the grep results
            const grepOutput = fs.readFileSync('./sources-referencing-closed-issues.txt', 'utf8');
            
            if (grepOutput) {
              const issueBody = context.payload.issue.body;
              const issueLabels = context.payload.issue.labels.map(label => label.name);

              // Reopen the issue
              await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.payload.issue.number,
                  state: 'open'
              });

              // Add a comment warning the user
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                body: 'The following tests are disabled due to this issue. Reenable them before closing the issue.\n\n${{ grepOutput }}'
              });

              core.warning(grepOutput);
            }