name: Check disabled tests
run-name: Checking for closed issues referenced in source at ${{ github.ref }} 🚀
on: 
    issues:
      types:
        - closed 
jobs:
 CheckDisabledTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Grep for the issue 
        run : grep -rHn "#${{ github.event.issue.number }}" --include="*.cs" . > sources-referencing-closed-issues.txt || true
      - name: Checking grep resuls
        uses : actions/github-script@v6
        with: |
          const fs = require('fs');
            
          // Read the grep results
          const grepOutput = fs.readFileSync('./sources-referencing-closed-issues.txt', 'utf8');
          
          if (grepOutput) {
            core.warning(grepOutput);
          }