name: Check disabled tests
run-name: Checking ${{ github.ref }} 🚀
on: 
    issues:
      types:
        - closed 
jobs:
 CheckDisabledTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check
        uses: actions/github-script@v6
        with: 
          script : core.warning('---> Issue ${{ github.event.issue.number }} was closed. Checking if any tests were disabled.');