name: Check disabled tests
run-name: Checking ${{ github.ref }} 🚀
on: 
    issues:
      types:
        - closed 
jobs:
 CheckDisabledTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check
        run : |
            grep -Hn "#${{ github.event.issue.number }}" **/*.cs > /tmp/sources-referencing-closed-issues.txt
            if [ $? -neq 0 ]; then
              while IFS=: read -r errorPath errorLine errorContent; do
                  echo "::error file=$errorPath,line=$errorLine,title=$errorContent::Missing semicolon"
              done < /tmp/sources-referencing-closed-issues.txt
            fi