name: Test
on:
  pull_request:
    types: [opened, edited, reopened, labeled, unlabeled, synchronize]
    branches:
      - "*"

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            var issuesOrPRReferences = context.payload.pull_request.body;
            core.notice(issuesOrPRReferences);
